# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-11 06:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=35, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Film_name', models.CharField(max_length=25, unique=True)),
                ('Year', models.IntegerField()),
                ('Rating', models.CharField(choices=[(b'T', b'Tharumaaruu - T'), (b'M', b'Massu - M'), (b'A', b'Attu - A'), (b'V', b'Verithanam - V')], default=b'V', max_length=80)),
                ('Duration', models.IntegerField()),
                ('Release_date', models.DateTimeField()),
                ('User_rating', models.DecimalField(decimal_places=1, default=b'0.0', max_digits=10)),
                ('Display_Image', models.ImageField(upload_to=b'Disp/')),
                ('Banner_Image', models.ImageField(upload_to=b'Banp/')),
                ('Trailer', models.URLField(blank=True)),
                ('Description', models.TextField()),
                ('Director', models.CharField(max_length=80)),
                ('Writer', models.CharField(max_length=80)),
                ('Metascore', models.IntegerField()),
                ('User_Review', models.IntegerField()),
                ('Critic_Review', models.IntegerField()),
                ('Popularity', models.IntegerField()),
                ('Created_Date', models.DateTimeField()),
                ('Modified_Date', models.DateTimeField()),
                ('CreatedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('country', models.ManyToManyField(to='films.Country')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genres', models.CharField(max_length=39, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.CharField(max_length=5, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='film',
            name='genres',
            field=models.ManyToManyField(to='films.Genre'),
        ),
        migrations.AddField(
            model_name='film',
            name='stars',
            field=models.ManyToManyField(to='films.Stars'),
        ),
    ]
