# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-11 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='film_name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
