# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-26 15:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='genres',
            new_name='country',
        ),
    ]
